const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const COUNTER_RESET = "COUNTER_RESET";
const INCREMENT_BY_AMOUNT = "INCREMENT_BY_AMOUNT";
const DECREMENT_BY_AMOUNT = "DECREMENT_BY_AMOUNT";
const UPDATE_UPPER_LIMIT_REACHED = "UPDATE_UPPER_LIMIT_REACHED";
const UPDATE_LOWER_LIMIT_REACHED = "UPDATE_LOWER_LIMIT_REACHED";
const UPDATE_NUMERICAL_VALUE = "UPDATE_NUMERICAL_VALUE";
const UPDATE_TOAST = "UPDATE_TOAST";

export default {
  INCREMENT,
  DECREMENT,
  COUNTER_RESET,
  INCREMENT_BY_AMOUNT,
  DECREMENT_BY_AMOUNT,
  UPDATE_UPPER_LIMIT_REACHED,
  UPDATE_LOWER_LIMIT_REACHED,
  UPDATE_NUMERICAL_VALUE,
  UPDATE_TOAST,
};
